language: cpp
sudo: required

os:
  - windows
  - linux
  - osx

osx_image: xcode11.3

dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmd /C "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then source build/InstallMono.sh; fi
  - build/InstallNugets.sh  
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then PREMAKE=build/premake5.exe; elif [ "$TRAVIS_OS_NAME" = "linux" ]; then PREMAKE=build/premake5-linux-64; else PREMAKE=build/premake5-osx; fi
  - $PREMAKE --file=build/scripts/LLVM.lua download_llvm

script: |
  - if [ "$TRAVIS_OS_NAME" = "windows" ] then $PREMAKE --file=build\premake5.lua %VS_VERSION% --arch=%PLATFORM% && msbuild.exe %BUILD_PATH%\CppSharp.sln; else then build/Compile.sh; fi
  - build/RunTests.sh
