language: cpp

install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update -qq
  - sudo apt-get install -q mono-devel nuget
  - build/premake5-linux --file=build/premake4.lua gmake
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - config=debug_x32 make -C build/gmake/
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe build/gmake/lib/Debug_x32/CppSharp.*Tests*.dll
