# Reference: http://www.appveyor.com/docs/appveyor-yml
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

matrix:
  fast_finish: true

os: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

environment:
  VS_VERSION: 2019
  DEPS_PATH: '%APPVEYOR_BUILD_FOLDER%\deps'
  LLVM_PATH: '%APPVEYOR_BUILD_FOLDER%\deps\llvm'
  BUILD_PATH: '%APPVEYOR_BUILD_FOLDER%\build\vs%VS_VERSION%'
  LIB_PATH: '%APPVEYOR_BUILD_FOLDER%\build\vs%VS_VERSION%\lib\%CONFIGURATION%_x64'
  ARTIFACT_NAME: '%APPVEYOR_PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-vs%VS_VERSION%.zip'
  GITHUB_ACCESS_TOKEN:
    secure: CrxPDgxTKC9ZRvFjttpRPO+e1DT8s0Zkk9HrAmHOIzDkOfFbbu1iTm/yJjZ2eDcd

init:
  - git config --global core.autocrlf true

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\%VS_VERSION%\Community\Common7\Tools\VsDevCmd.bat"
  - build\premake5.exe --file=build\scripts\LLVM.lua download_llvm

build_script:
  - build\premake5.exe --file=build\premake5.lua vs%VS_VERSION% --arch=x86
  - msbuild %BUILD_PATH%\CppSharp.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - nunit3-console %LIB_PATH%\CLI.Tests.CLI.dll %LIB_PATH%\Common.Tests.CLI.dll %LIB_PATH%\Common.Tests.CSharp.dll %LIB_PATH%\CppSharp.Generator.Tests.dll %LIB_PATH%\CSharp.Tests.CSharp.dll %LIB_PATH%\Encodings.Tests.CSharp.dll %LIB_PATH%\NamespacesDerived.Tests.CSharp.dll %LIB_PATH%\StandardLib.Tests.CLI.dll %LIB_PATH%\VTables.Tests.CSharp.dll --result=myresults.xml;format=AppVeyor
  - build\premake5.exe --file=build\premake5.lua vs%VS_VERSION% --arch=x64
  - msbuild %BUILD_PATH%\CppSharp.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - nunit3-console %LIB_PATH%\CLI.Tests.CLI.dll %LIB_PATH%\Common.Tests.CLI.dll %LIB_PATH%\Common.Tests.CSharp.dll %LIB_PATH%\CppSharp.Generator.Tests.dll %LIB_PATH%\CSharp.Tests.CSharp.dll %LIB_PATH%\Encodings.Tests.CSharp.dll %LIB_PATH%\NamespacesDerived.Tests.CSharp.dll %LIB_PATH%\StandardLib.Tests.CLI.dll %LIB_PATH%\VTables.Tests.CSharp.dll --result=myresults.xml;format=AppVeyor
  
test:
  assemblies:
    except:
      - '*.dll'

#---------------------------------#
#    parser bindings generation   #
#---------------------------------#

on_success:
  #- git config --global user.name "CppSharp CI"
  #- git config --global user.email "joao+cppsharp-ci@tritao.eu"
  #- git config --global credential.helper store
  #- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  #- git remote set-url origin https://github.com/mono/CppSharp.git
  #- git checkout master
  #- '%LIB_PATH%\CppSharp.Parser.Gen.exe'
  #- 'git commit -a -m "CI: Re-generated the parser bindings"'
  #- git push

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

after_build:
  - echo 'Preparing artifacts...'
  - 7z a %ARTIFACT_NAME% %LIB_PATH%\CppSharp* %LIB_PATH%\lib
  - appveyor PushArtifact %ARTIFACT_NAME%

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  release: 'CppSharp'
  description: "Latest successful CI builds of branch 'master'"
  provider: GitHub
  auth_token:
    secure: tSYxyXeLtE0f6ZsXsGaHZEAw5Nj4TcgN/rx8uCfPnRjcE55OLAVn/8WXEiovNXLt
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
